# Generated by Django 2.2.2 on 2019-07-01 06:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190701_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpage',
            name='date',
        ),
        migrations.AlterField(
            model_name='featuredpage',
            name='body',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(blank=True)), ('button', wagtail.core.blocks.CharBlock(blank=True)), ('paragraph', wagtail.core.blocks.CharBlock(blank=True))]),
        ),
    ]
