# Generated by Django 2.2.2 on 2019-07-01 07:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('web', '0004_teamindexpage_teampage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamPage',
            new_name='TeamMemberPage',
        ),
    ]
