# Generated by Django 2.2.2 on 2019-06-28 09:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190628_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('button', wagtail.core.blocks.CharBlock(blank=True)), ('paragraph', wagtail.core.blocks.CharBlock(blank=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True)), ('quote', wagtail.core.blocks.BlockQuoteBlock(blank=True))]),
        ),
    ]
