# Generated by Django 2.2.2 on 2019-07-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_newslettersignupfrom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSignUpFrom',
            new_name='NewsletterSignUpForm',
        ),
    ]
