# Generated by Django 2.2.2 on 2019-07-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190702_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='title',
            new_name='name',
        ),
    ]
