# Generated by Django 2.2.2 on 2019-07-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20190702_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
