# Generated by Django 2.2.2 on 2019-07-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_delete_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
            ],
        ),
    ]
