# Generated by Django 2.2.2 on 2019-07-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_newslettermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterModel',
            new_name='Snippet',
        ),
    ]
