# Generated by Django 2.2.2 on 2019-07-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20190702_1113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
