# Generated by Django 2.2.2 on 2019-07-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20190702_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='page',
            new_name='newsletter_form_page',
        ),
    ]
