# Generated by Django 2.2.2 on 2019-07-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('web', '0021_mycustomsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_left', models.CharField(max_length=250)),
                ('list_item1_left', models.CharField(blank=True, max_length=250, null=True)),
                ('list_item2_left', models.CharField(blank=True, max_length=250, null=True)),
                ('list_item3_left', models.CharField(blank=True, max_length=250, null=True)),
                ('list_item4_left', models.CharField(blank=True, max_length=250, null=True)),
                ('list_item5_left', models.CharField(blank=True, max_length=250, null=True)),
                ('list_item6_left', models.CharField(blank=True, max_length=250, null=True)),
                ('title_right', models.CharField(max_length=250)),
                ('list_item1_right', models.CharField(blank=True, max_length=250, null=True)),
                ('list_item2_right', models.CharField(blank=True, max_length=250, null=True)),
                ('list_item3_right', models.CharField(blank=True, max_length=250, null=True)),
                ('list_item4_right', models.CharField(blank=True, max_length=250, null=True)),
                ('list_item5_right', models.CharField(blank=True, max_length=250, null=True)),
                ('list_item6_right', models.CharField(blank=True, max_length=250, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'footer settings',
            },
        ),
    ]
