# Generated by Django 2.2.2 on 2019-07-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='logo_left',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='logo_right',
            field=models.ImageField(default='images/areto.svg', upload_to='media/'),
        ),
    ]
