# Generated by Django 2.2.2 on 2019-07-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20190703_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='logo_right',
            field=models.ImageField(default='images/areto.jpg', upload_to=''),
        ),
    ]
